// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhwjNoPce2eUQ8mrhnAruWKFU7g-7lZbg',
    appId: '1:552664318312:web:9c46f394518d0f1e6916dd',
    messagingSenderId: '552664318312',
    projectId: 'abideverse',
    authDomain: 'abideverse.firebaseapp.com',
    storageBucket: 'abideverse.firebasestorage.app',
    measurementId: 'G-GNN8HZ4112',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgryuKzManAyQNmoDaaYs63wjNWRJV3ak',
    appId: '1:552664318312:android:433d9edc7a9f427f6916dd',
    messagingSenderId: '552664318312',
    projectId: 'abideverse',
    storageBucket: 'abideverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkflNopScP3a9d4gPALrUSuHS7KJ3aK2s',
    appId: '1:552664318312:ios:2d0c15f8dc820fae6916dd',
    messagingSenderId: '552664318312',
    projectId: 'abideverse',
    storageBucket: 'abideverse.firebasestorage.app',
    iosClientId: '552664318312-bfdl52co476u4qrr35khfapj6u9vnah2.apps.googleusercontent.com',
    iosBundleId: 'com.joyolord.abideverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkflNopScP3a9d4gPALrUSuHS7KJ3aK2s',
    appId: '1:552664318312:ios:2d0c15f8dc820fae6916dd',
    messagingSenderId: '552664318312',
    projectId: 'abideverse',
    storageBucket: 'abideverse.firebasestorage.app',
    iosClientId: '552664318312-bfdl52co476u4qrr35khfapj6u9vnah2.apps.googleusercontent.com',
    iosBundleId: 'com.joyolord.abideverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhwjNoPce2eUQ8mrhnAruWKFU7g-7lZbg',
    appId: '1:552664318312:web:6e3ba723120965866916dd',
    messagingSenderId: '552664318312',
    projectId: 'abideverse',
    authDomain: 'abideverse.firebaseapp.com',
    storageBucket: 'abideverse.firebasestorage.app',
    measurementId: 'G-DMGDS51T04',
  );

}